### ISSUE TITLE
Hide "People also ask" and "Remove everything but simple results" block page content

### ISSUE THREAD

**Issue by koitsu** [letsblockit/letsblockit#170]
### What filter does this issue target?

google-search-cleanup

### What changes should be made?

Two filters incorrectly block/mangle output on some Google search result pages:

* Hide the "People also ask" contextual content: `google.*###rso > div:has(div.related-question-pair)`
* Remove everything but simple results in the text search: `google.*###rso > :not(div.g):not(:has(:scope>div.g))`

If either of these are enabled, search results will appear briefly then the main content area will go blank, leaving only Google's pagination footer.  I can try to get a GIF demonstrating this if necessary, but it's easy to reproduce:

1. Ensure one or both of the above filters are enabled
2. Visit https://www.google.com/
3. Search for: **romance of the three kingdoms**
4. Disable both the filters + save/apply + reload page and see expected results

### Did you write a uBlock filter solving this?

I have not found a workaround at this time, other than disabling the above two filters.  (The last workaround I DID have was prior to switching to LetsBlockIt, and that workaround stopped working about a week ago when Google changed something.)

**Comment by koitsu** [comment]
Verification using the DOM logger that the impact is exactly as I stated:

![screenshot](https://user-images.githubusercontent.com/8430773/172161092-ef6fd18d-5e44-49a3-bf27-f6f7843aea66.png)

**Comment by xvello** [comment]
Thanks for your report @koitsu,

>  that workaround stopped working about a week ago when Google changed something

My best guess is that google is deploying a redesign that changes the markup, and breaks filters. That's to be expected, and that's one of the reasons for the project (we can fix it for the other users). Where google makes it harder than others is that this type of change can be deployed progressively over several weeks. For example, I cannot reproduce the issue from France, with either Firefox nor Chromium.

> search results will appear briefly then the main content area will go blank

Your account could also be part of [an A/B test](https://en.wikipedia.org/wiki/A/B_testing) and that new design might never be rolled out. This could explain why the markup changes AFTER the results are loaded :confused: 

As I'm currently flying blind here, could you please:

- triple check that `Hide the "People also ask" contextual content` alone triggers the bug (by making sure you [force-refresh the list](letsblock.it/help/refresh-list)). The other filter is a pretty blunt weapon (the documentation says so, and it would definitely have the power to hide everything), but this one is pretty targeted, so I'd love a confirmation here

- send me a dump of the page markdown to the email [listed here](https://letsblock.it/help) (or as a file attachement here), so that I can inspect it and design an alternative filter:
  - in either Firefox or Chrome, open the search page and let the results load then hide
  - open the inspector panel (right click > inspect)
  - right click on the `html` element at the top, and chose "Copy outer HTML"
  - paste that into a `.html` file

**Comment by koitsu** [comment]
Thanks for the response @xvello -- I'll work on getting you what you need.  Currently I'm off trying to brute-force this through a different manner.  But I can get you the Markdown in question if I am unable to succeed :)

**Comment by koitsu** [comment]
Email sent with attachment.

**Comment by xvello** [comment]
Thanks for the markup dump, it's very helpful.

So.... this new design has even more nested divs, and even less semantic classes to match on. That's gonna be fun :/

The "People also ask" filter does indeed hide everything, because results are not direct children of `#rso` anymore, but nested way deeper under `#rso`.  They do seem to be direct children of a `#kp-wp-tab-overview` element now, so replacing `#rso` with `#kp-wp-tab-overview` might fix some filters.

As for the "Remove everything but simple search results", the organic results still have their `g` class, but are buried down into lots of nested divs, I'll need to thinker with it a bit more to find a filter that has acceptable performance.

**Comment by xvello** [comment]
Hello @koitsu, so far I have not received any other report of this issue happening, so I added a warning to the filter description directing people here.

Could you please upgrade me on whether the issue still occurs, or whether you have the old design served to you again? Also, is it high priority or do you have a workaround in place?

**Comment by koitsu** [comment]
@xvello I decided to re-test everything, as there's been some Chrome updates since my original report and of course Google probably rolling out site changes regularly anyway.

The short answer: things now are different than before.  Sadly, both better and worse at the same time.

`google.*###rso > div:has(div.related-question-pair)` seems to work correctly now.  That's good.

Additionally, the issue of there being blank content (and thus no navigation buttons) is also gone.  So that's also good.

However, `google.*###rso > :not(div.g):not(:has(:scope>div.g))` now causes different problems.  Some content (search result entries) is now being filtered that should not be.  This is hard to demonstrate in a screenshot because the content which is missing requires me to scroll down in the search results (although admittedly the first/top search result is also filtered).

I'll send you an Email with another HTML dump and you'll hopefully see what I mean.

This could be further results of being an A/B test subject, but of course I have no way to determine that reliably (nor opt-out).

So for now, I can't use `google.*###rso > :not(div.g):not(:has(:scope>div.g))`.  But I can live with that.

(Footnote: in the latest Chrome, you no longer can right-click an element and get a context menu to open. Instead, you now have to select the line/element you want (left-click), then left-click the grey ellipsis (triple-dots) that are shown to the left of the line/element, and choose Copy/etc. from there.  I really wish these companies would stop changing UI behaviour.)

**Comment by xvello** [comment]
Heya @koitsu, I empathize with your frustration, but I feel kind of powerless without a wider rollout. I do expect a couple of updates per year for each filter, but won't be able to play cat and mouse.

After a year on duckduckgo, I switched to kagi.com and I find it really worth the price. Being able to raise/lower domain priorities and lenses really changes the search experience.

**Comment by xvello** [comment]
Hopefully fixed with the new filter release, don't hesitate to ping if there are adjustments to be made.

**Comment by koitsu** [comment]
@xvello I updated my filters 3 days and so far so good. Thank you so much!
