### ISSUE TITLE
Please add a filter to block facebook's sponsored and suggested... annoyances

### ISSUE THREAD

**Issue by pitsi** [letsblockit/letsblockit#220]
### What website(s) would this filter apply to?

facebook.com

### What content should be blocked?

Sponsored and suggested posts mainly.

### What options should be offered?

Block sponsored and block suggested posts.

### Did you write a custom uBlock filter already?

No, but other's have. There is this set of filters from the ublock's wiki on reddit, but some of them no longer work since last April or so.
https://old.reddit.com/r/uBlockOrigin/wiki/solutions

**Comment by xvello** [comment]
Hello @pitsi, and thanks for your suggestion. As stated in [the contributing guidelines](https://letsblock.it/help/contributing), Meta's websites are explicitly out of scope for this project. Even if it was not, the [EasyList](https://github.com/easylist/easylist) project would be a better home for this kind of rules, because they don't need to be customizable.

For your information, the facebook.com markdown is a hot pile of poop, because they are purposely obfuscating it to make it harder and harder to block sponsored posts. Frequent breakages are to be expected.

**Comment by pitsi** [comment]
Thank you for the information.

The truth is that I have tried a lot of other lists, especially from this dev here whose lists are considered really good, but I still see sponsored and suggested trash. So, any other suggestions are welcome.
https://github.com/kowith337/PersonalFilterListCollection/

**Comment by xvello** [comment]
Heya @pitsi,

Most rules are expected to break once or twice a year when features are added or a redesign is deployed, and that's fine. It's even part of Let's Block It's value proposition: instead of having you fish for an updated rule in a wiki or a forum, the fix will be automatically delivered to you. While most of big tech has a *laisser-faire* attitude to tinkerers, the people at facebook have been actively fighting efforts to build alternative clients and de-clutter their websites, as [the wiki you linked](https://old.reddit.com/r/uBlockOrigin/wiki/solutions#wiki_facebook) illustrates.  My opinion is that it's not a good use of resources for the adblock community to continue playing that cat-and-mouse game when there's so much more to improve elsewhere.

On a more personal note, I am really committed to maintain this project for the long term. For that to work I need to ensure it does not bring toxicity in my life, and it my opinion that company is toxic to the bone. Because I never had a facebook account and never will, I'm not able nor willing to help with that company's websites. I hope that this project still brings you value, and that the upcoming weekend will treat you good!
