### ISSUE TITLE
Is it possible to link directly login & register pages?

### ISSUE THREAD

**Issue by 07416** [letsblockit/letsblockit#270]
The 'login' element on the [letsblock.it](https://letsblock.it/) pages redirects to `https://letsblock.it/user/forms/registration?flow=*` ('create account'), the 'login' item on this page in turn to `https://letsblock.it/user/forms/login?flow=*`, and 'recover password' to `/recovery?flow=`.

What is the multi-character string after `?flow=` ? Is this some identifier? Attempting to access `https://letsblock.it/user/forms/login` and all variations I tried result in a server error.

I'd prefer bookmarking the login page and may share direct registration URLs to others, for instance.

**Comment by xvello** [comment]
Hello @07416, thanks for your suggestion!

The flow ID is a one-time unique identifier used to track state. If you're curious, you can have a look at [the Kratos documentation](https://www.ory.sh/docs/kratos/self-service) for the technical details (letsblock.it uses the server-side app flow described in the first part). Clicking on the `Login` button validates a form, which is why you cannot bookmark it.

I added an alias handler in https://github.com/letsblockit/letsblockit/pull/271, so that you can now bookmark https://letsblock.it/user/action/loginOrRegistration to get the login / registration flow started, if you're already logged in, you will be redirected to the homepage instead. Hope that works for you!

**Comment by 07416** [comment]
@xvello Could you create an another alias for the 'login' tab (and why not for 'recover password', at once)?

![image](https://user-images.githubusercontent.com/14923168/196024310-05e426d7-71aa-4826-8e72-1d6cfe5c88a6.png)
