### ISSUE TITLE
Disable youtube membership popups

### ISSUE THREAD

**Issue by Spark-NV** [letsblockit/letsblockit#274]
### What website(s) would this filter apply to?

Any youtube video

### What content should be blocked?

The popup that says to "become a member for $10".

It asks you to become a member of a specific persons channel for 10$ per month. this popup pops up on the bottom left when it does popup and seems to be random? or maybe its whenever you first visit a new persons channel that you havnt seen before? not sure what triggers the popup.

### What options should be offered?

disable the popup?

**Comment by xvello** [comment]
Hello @Spark-NV, and thanks for opening this issue and https://github.com/letsblockit/letsblockit/issues/275. I will reply to both here. Unfortunately, I cannot write a rule for these as I am not served these popups in France.

In order to keep the scope of this project reasonable, I try to avoid any overlap with the other standard lists. Because these two popup clearly fall into the annoyances category (and anyone enabling these lists would want these blocked), they are better suited in either the [AdguardFilters](https://github.com/AdguardTeam/AdguardFilters) or [EasyList](https://github.com/easylist/easylist) annoyance lists. 

I checked both repositories and could not find an issue or commit covering these new popups, so they need to be made aware of them. I recommend opening one single issue (for both types, with screenshots) in either repository to get the ball rolling. I will close these two issues as `out-of-scope` for this project and hope they'll be able to quickly look into these.
