### ISSUE TITLE
Hide YouTube Chat Window

### ISSUE THREAD

**Issue by jason-riddle** [letsblockit/letsblockit#277]
### What website(s) would this filter apply to?

www.youtube.com

### What content should be blocked?

The chat window for livestreams.

### What options should be offered?

Not sure.

### Did you write a custom uBlock filter already?

```
! Hide Youtube Chat
www.youtube.com###chat
```

**Comment by xvello** [comment]
Hello @jason-riddle, thanks for opening this issue. 

Turns out this is already implemented as the "Hide the live chat when viewing streams" option of https://letsblock.it/filters/youtube-cleanup. FYI, I added `:remove()` to stop the javascript that retrieves the message stream and save some CPU. Otherwise, the element is hidden but still updating.

**Comment by jason-riddle** [comment]
Ah, missed that. Closing.
