### ISSUE TITLE
Hide Youtube #shorts

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#305]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

A "Shorts" section/row is displayed across a channel's "Home" page even though the "Hide Youtube #shorts" filter is applied.
Browser is Edge.

**Comment by xvello** [comment]
Hello @3DWORX-SA ,

[This rule](https://github.com/letsblockit/letsblockit/blob/aa8f48c84cadc59f7e33867317d8552916be3d63/data/filters/youtube-shorts.yaml#L9) is tailored to hide that homepage shelf.

Can you please:

- post a screenshot of it, so that I can check we're talking about the same thing
- tell me what version of uBlockOrigin is installed on your browser
- test with uBlock Origin on Firefox if you can, to check it's not a browsers specific issue

Thanks!

**Comment by 3DWORX-SA** [comment]
Hi Xavier,

uBlock Origin is v1.45.2

***@***.***

The channel https://www.youtube.com/c/NotWhatYouThink shows shorts in row 2:

***@***.***


The rule you refer to is third in my list after removing and reapplying the filter:
***@***.***

I don't have Firefox installed. If you don't figure it out then I could try it on another laptop.

Regards

**Comment by xvello** [comment]
@BPower0036 's fix has been deployed, you'll get it within 24 hours, or earlier if you [refresh your list](https://letsblock.it/help/refresh-list) to grab it!
