### ISSUE TITLE
Remove non-organic YouTube search results

### ISSUE THREAD

**Issue by RianQuenlin** [letsblockit/letsblockit#338]
### What website(s) would this filter apply to?

YouTube

### What content should be blocked?

For You, Previously Watched, People Also Watched, and other irrelevant drivel in the search results.

### What options should be offered?

The only difference is the text string at the end, adding/removing lines as needed is an easy enough task. Might not be compatible with different languages

### Did you write a custom uBlock filter already?

```
www.youtube.com##ytd-shelf-renderer.style-scope:has(span:has-text(/for you/i))
www.youtube.com##ytd-shelf-renderer.style-scope:has(span:has-text(/previously watched/i))
www.youtube.com##ytd-shelf-renderer.style-scope:has(span:has-text(/related to your search/i))
www.youtube.com##ytd-shelf-renderer.style-scope:has(span:has-text(/channels new to you/i))
www.youtube.com##ytd-shelf-renderer.style-scope:has(span:has-text(/From related searches/i))
www.youtube.com##ytd-shelf-renderer.style-scope:has(span:has-text(/Learning related/i))
! Removes "People also search for"
www.youtube.com##ytd-horizontal-card-list-renderer.ytd-item-section-renderer.style-scope
```

**Comment by xvello** [comment]
Hello @RianQuenlin, thanks for your idea!

Unless there's really no other way, I prefer to avoid matching on displayed strings (with `:has-text` or other operators), because:
  - this breaks the rules if the display language is different from yours
  - these rules usually break more often

What about removing all shelves?

```
www.youtube.com##ytd-search ytd-item-section-renderer ytd-shelf-renderer:style(border: 2px dashed red !important)
www.youtube.com##ytd-search ytd-item-section-renderer ytd-horizontal-card-list-renderer:style(border: 2px dashed red !important)
```

The `:style()` operator adds a red border, to test the scoping of the rules, remove it to hide the matching elements.

**Comment by xvello** [comment]
New template is available at https://letsblock.it/filters/youtube-search-cleanup, thanks again for the idea!
