### ISSUE TITLE
Hide old Youtube videos from the subscription feed

### ISSUE THREAD

**Issue by joecbr** [letsblockit/letsblockit#349]
### What website(s) would this filter apply to?

https://www.youtube.com/feed/subscriptions

### What content should be blocked?

The idea is to have the ability to see only videos that were released in the last X period, the last 3 months for example, in the Youtube subscription feed.

### What options should be offered?

Change the period for the videos that will be displayed. 

### Did you write a custom uBlock filter already?

No, I have not.

**Comment by JohnyP36** [comment]
I don't know if this is necessary, as Youtube orders the videos from new to old. If you stop scrolling after you are three months back in time there is no need for a rule. Or am I wrong?

**Comment by joecbr** [comment]
I made it work using the below single-line entry. Not sure how good it is but it removed the videos older than 4 months from the feed.

`www.youtube.com##span.ytd-grid-video-renderer.style-scope:nth-of-type(2):has-text(/\b[4-9] months\b/i):upward(ytd-item-section-renderer)`

**Comment by joecbr** [comment]
> I don't know if this is necessary, as Youtube orders the videos from new to old. If you stop scrolling after you are three months back in time there is no need for a rule. Or am I wrong?

@JohnyP36, you are correct. Maybe I am too pick and want to keep my feed too clean. =]
We may close this request if it will not help anyone else.

**Comment by JohnyP36** [comment]
> @JohnyP36, you are correct. Maybe I am too picky and want to keep my feed too clean. =] I'll close this request since it may not help anyone else.

Maybe we can wait for @xvello 's response. If he thinks it is a good idea, we can implement your rule in one of the youtube templates.

**Comment by xvello** [comment]
Hello @joecbr, thanks a lot for opening this issue!

I agree with @JohnyP36 that this rule might be too specific to be worth adding to the common corpus, but that's exactly why we support [adding custom rules](https://letsblock.it/filters/custom-rules) to your list. These rules will be synchronized on all your devices like our common templates.

My main reservation about including it in the common corpus is that fact that it will only work in English, because it matches the `months` word. Our contributors and users are from all over the word, and we try hard to match on semantic / structure selectors so that our rules work on all languages. I cannot find a language-agnostic way to write that rule though.
