### ISSUE TITLE
YouTube: filter out Shorts (But only for Subscriptions Page: https://www.youtube.com/feed/subscriptions)

### ISSUE THREAD

**Issue by fossist** [letsblockit/letsblockit#381]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

Youtube Subscriptions Page is the only place where Shorts become unbearable. Youtube fixed the channel's page by creating different tabs for shorts, videos and livestreams. But Subscriptions Page is the only place where they didn't implement this.

Is it possible to block shorts only from Subscriptions Page: https://www.youtube.com/feed/subscriptions?

I want shorts to be available everywhere on youtube except the Subscriptions Page.

Any help would be appreciated. 😇😇

**Comment by xvello** [comment]
Hello @fossist, thanks for opening this issue!

Customization is at the core of the project's goals, but it comes with a significant maintenance overhead: make sure that rules can work separately and together, test the different combinations on every PR, ask for configuration when handling issues...

The youtube-shorts template is the [most frequently updated template](https://github.com/letsblockit/letsblockit/pulls?q=is%3Apr+youtube-shorts) because of website changes, and the frequency of changes does not seem to slow down (right now the navbar rules are broken for some users, due to an ongoing design change). Once the situation settles for several months, I'll be happy to revisit that decision, but for now I prefer to avoid adding any configuration to this template.

**Comment by BPower0036** [comment]
@fossist try 
`www.youtube.com#?#ytd-browse[page-subtype="subscriptions"] .ytd-thumbnail[href^="/shorts/"]:upward(ytd-grid-video-renderer)`
`www.youtube.com#?#ytd-browse[page-subtype="subscriptions"] ytd-video-renderer:has(.ytd-thumbnail[href^="/shorts/"]):upward(ytd-item-section-renderer)`.
For those rules works.
