### ISSUE TITLE
Ads on Youtube

### ISSUE THREAD

**Issue by BabyGravy** [letsblockit/letsblockit#382]
### What website(s) would this filter apply to?

youtube.com

### What content should be blocked?

Ad in the top left panel.

### What options should be offered?

Block the ads.

### Did you write a custom uBlock filter already?

www.youtube.com##ytd-display-ad-renderer

www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[href*="&start_radio=1"])
www.youtube.com##ytd-search ytd-radio-renderer
www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-radio-renderer
www.youtube.com##ytd-player div.videowall-endscreen a[data-is-list=true]
www.youtube.com##ytd-ad-slot-renderer.style-scope
www.youtube.com##ytd-rich-grid-renderer
www.youtube.com##ytd-display-ad-renderer.style-scope > div:nth-child(1)

### Additional notes

Tried all that and it just wont hide the ads. Driving me nuts. Help please.
![Screenshot 2023-03-19 021556](https://user-images.githubusercontent.com/74304181/226160048-5c6380a0-45e2-4b62-9d07-b8ef2a160893.png)

**Comment by xvello** [comment]
Hello @BabyGravy, thanks for opening this issue!

As stated in [our contributing instructions](https://letsblock.it/help/contributing), blocking ads and trackers is out of the scope of this project, please contribute to [EasyList](https://easylist.to/) or [AdGuard](https://kb.adguard.com/en/general/adguard-ad-filters) instead.

This is because these projects do a great job at covering this scope, and duplicating efforts would be a waste of energy.
