### ISSUE TITLE
youtube-shorts: new design for subscription page breaks the template

### ISSUE THREAD

**Issue by veraverto** [letsblockit/letsblockit#385]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

<img width="759" alt="grafik" src="https://user-images.githubusercontent.com/18749953/229783767-db5ce54b-ce27-4d10-8db5-60905c252e10.png">
Here's a screenshot.

### Additional notes

I just re-installed the Shorts filter after I stopped using them for some months and was wondering if it was possible to block Shorts in the subscriptions. If I recall correctly it was possible before.

**Comment by PhantomFFR** [comment]
It should and did so until yesterday.

**Comment by xvello** [comment]
Hello @veraverto, thanks for reporting this issue!

These should indeed be filtered out, which means you are served a new design that breaks our rules. I cannot reproduce on my account though. Google is know for slowly releasing such changes, so we're not all affected yet, and it could be reverted before it hits everyone.

To help us update the rule, could you please copy the HTML for this new design in a comment here?

- right-click > inspect on one of the shorts
- locate the corresponding `ytd-grid-video-renderer` element, then right-click > copy > outer HTML
- paste it here

**Comment by veraverto** [comment]
Thanks for your reply @xvello! I've just tried to find the ytd-grid-video-renderer element but as just posted by @PhantomFFR I also couldn't find the element (see the screenshot below). Is there any other way I could help?

<img width="1511" alt="Bildschirm­foto 2023-04-04 um 18 36 15" src="https://user-images.githubusercontent.com/18749953/229859106-0f3ba652-81cc-46b5-92c9-399a73f92a35.png">

**Comment by xvello** [comment]
Thanks! I'll update the template accordingly!

> Certainly better than seeing the shorts, but worse than it was before yesterday, when real videos moved up nicely and the grid was completely filled out.

This has been an issue for the homepage for a while, and it looks like they just expanded that design to the subscriptions page now. Instead of allowing the browser to reflow the thumbnails as single list, their markup has these `ytd-rich-grid-row` elements for each row, that block that behavior.

**Comment by PhantomFFR** [comment]
I see, thanks for the explanation and the work as well. :)

I reckon for a Stylus or Greasemonkey-script the same safety concerns would apply? If it were possible to solve the reflow-issue for someone knowledgeable that is.

**Comment by xvello** [comment]
> I reckon for a Stylus or Greasemonkey-script the same safety concerns would apply? If it were possible to solve the reflow-issue for someone knowledgeable that is.

A Greasemonkey can do arbitrary modifications to the DOM, which would indeed allow such changes. The same safety concerns would also apply.

The uBO team does not want to give such broad capabilities, so that rule lists are not an attractive vector for attackers. I agree with that stance, that makes me less nervous about the public instance being compromised. They recently added the capability to inject custom CSS style, like we do in https://letsblock.it/filters/hackernews-darkmode. Someone with good CSS knowledge might be able to write some styles that force a correct reflow of the thumbnails.

**Comment by xvello** [comment]
Heya @veraverto @PhantomFFR  

The fix has just been deployed! Your browser will get the update in less than 24h, but you can [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it! Don't forget to remove the custom rule you added for testing.
