### ISSUE TITLE
GitHub: remove algorithmic feed and corporate changelog

### ISSUE THREAD

**Issue by mrjones2014** [letsblockit/letsblockit#424]
### What website(s) would this filter apply to?

github.com

### What content should be blocked?

The social-media-style algorithmic "For You" tab, the corporate changelog blog thingy above the "Explore repositories", and the ads that sometimes appear above that (like for GitHub Universe conference).

### What options should be offered?

An option to block or not block each of:

- The algorithmic tab
- The corporate changelog section
- The ads section above that

### Did you write a custom uBlock filter already?

Yes:

```
! the corporate changelog thingy
github.com##.dashboard-changelog.mb-4

! the ads section above that
github.com##.js-notice

! the algorithmic "for you" tab
github.com###feed-next
```

**Comment by xvello** [comment]
Hello @mrjones2014, thanks a lot for the idea and the rules!

Would you be interested in opening a PR to add that template? You could copy and modify [linuxfr-cleanup.yaml](https://github.com/letsblockit/letsblockit/blob/main/data/filters/templates/linuxfr-cleanup.yaml), the details of the file format are described in https://github.com/letsblockit/letsblockit/blob/main/data/filters/README.md

We might want to extend the `"for you" tab` rule to also hide the content if possible: if a user has their homepage set to "for you" (looks like it's becoming the default?), they'd see the algorithmic content under the "following" tab heading and be pretty confused. Clicking on "following" would fix it, but it's not obvious.

**Comment by mrjones2014** [comment]
Yup, definitely I can submit a PR tomorrow!

> We might want to extend the "for you" tab rule to also hide the content if possible: if a user has their homepage set to "for you" (looks like it's becoming the default?), they'd see the algorithmic content under the "following" tab heading and be pretty confused. Clicking on "following" would fix it, but it's not obvious.

I’d actually done this already at one point but the rules seem to be missing now, I must’ve done it on a different browser. I’ll reimplement that tomorrow and submit a PR.

**Comment by xvello** [comment]
Great news! Ping me if you hit any snag with the contribution flow, any feedback to improve it would be welcome.

I'd go with a generic `github-cleanup` name (we can add more options, and split it later if it becomes too big), and two options for now:

- 'Hide GitHub news (changelog, events) from the homepage' for the two first rules
- 'Hide the new "For you" homepage feed' for the tab + hopefully the contents if that was the selected mode

**Comment by xvello** [comment]
Also, as I commented in https://github.com/letsblockit/letsblockit/issues/422#issuecomment-1548417092, we've had several cases of rules matching in unintended places, due to developers reusing identifiers in different pages, so I try to make rules a bit more specific now.

Unfortunately, Github does not have a lot of semantic information in their markup, so it will be difficult to get things to be very specific. Adding more parent containers to the stuff I'm matching is my go-to action in that case, for example:

- For the changelog stuff, we could write `github.com##aside .dashboard-changelog.mb-4` to also list one parent
- For the feed, `github.com###dashboard .js-feeds-tabs #feed-next` is a more specific version of the button rule, and `github.com###dashboard tab-container div[aria-labelledby="feed-next"]` seems to match the content

**Comment by mrjones2014** [comment]
Busy day at work today so I probably won't get to this today but I will submit a PR eventually.

**Comment by xvello** [comment]
Hey @mrjones2014 

It can now find it at https://letsblock.it/filters/github-cleanup, thanks for the idea! Don't hesitate to suggest more rules and give any feedback on the general usability.
