### ISSUE TITLE
Consider filtering actions not supported by uBlock

### ISSUE THREAD

**Issue by solna86** [letsblockit/letsblockit#47]
This is a great initiative to curate custom filters that are not supplied by uBlock, e.g. to get rid of those annoying Google GPDR consent popups.

However, uBlock has a relatively narrow scope. There is a large class of annoyances that cannot be dealt with by uBlock. Mainly, those that require rewriting links or blocking some dynamic requests.

There are two great addons dealing with these:

* ClearURL
* RequestControl

I like RequestControl better because it's not simply devoted towards sanitizing URLs. It also allows very general rules. For example, redirect all URLs dynamically from www.reddit.com to old.reddit.com. I think that uBlock + RequestControl can fulfill most privacy, security and annoyance requirements while being a lot less brittle than tools like GreaseMonkey.

Besides, some ClearURL rules are too aggressive and break some sites.

Have you considered supporting either of this in your letsblock.it initiative?

**Comment by xvello** [comment]
Hello @solna86 and thanks for your input!

(Side note: uBlockO now supports AdGuard's [removeparam directive](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#removeparam), that seems to cover a big chunk of ClearURL's scope)

I already have plans to allow users to maintain several lists, so supporting another rule format would not be very disruptive (mostly frontend work to manage two lists). A do have reservations about whether the letsblockit project would add enough value for these extensions though. My ambition is to cover the middle-ground between:

- filters that are OK to have in uBlockO/AdGuard's lists (either default or optional lists), because there is a consensus the element should be hidden
- very specific filters one can do themselves via the element zapper

Would you be OK sharing half a dozen rules you'd see yourself contributing to the corpus? For now, I want to focus on onboarding filter contributors on the uBlockO scope, but am open to re-evaluating this later if several people manifest interest for this.

**Comment by krystian3w** [comment]
Zapper don't create filters, delete node once.

**Comment by xvello** [comment]
> Zapper don't create filters, delete node once. Rare needed is share filters with :remove().
Hello @krystian3w, I'm not sure I understand your point here, could you please reformulate it?

**Comment by krystian3w** [comment]
> via the element zapper

https://github.com/gorhill/uBlock/wiki/Element-zapper

**Comment by BPower0036** [comment]
Maybe see: 
- https://github.com/DandelionSprout/adfilt/raw/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt (ClearURL for uBO)
- https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt
- https://filters.adtidy.org/windows/filters/17.txt (AdGuard URL Tracking filter)

**Comment by krystian3w** [comment]
https://letsblock.it/filters/url-param-remover

other story is break page like `onet.pl` if few parameters was removed.

**Comment by garry-ut99** [comment]
uBO has recently added an experimental `href-sanitizer` scriptlet, which further enhances URL parsing capatibilities of uBO: https://github.com/uBlockOrigin/uBlock-issues/wiki/Resources-Library#href-sanitizerjs-

**Comment by HyperCriSiS** [comment]
It would be awesome to have templates for it on letsblock.it!
The extension currently has no proper platform to exchange custom made templates.
That's sad, because I also think that RequestControl is a very good addon with tons of possibilities. 
Theoretically it could replace many of those privacy addons.

**Comment by xvello** [comment]
I am closing this issue, as we concluded that neither of the two suggested extensions are a good fit for this project.

I'll be happy to evaluate other extensions as they are suggested though, but please open separate issues so that they are easier to manage.
