### ISSUE TITLE
shorts aren't filtered in the search result of mobile youtube

### ISSUE THREAD

**Issue by chedanix** [letsblockit/letsblockit#484]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

Please add the rule to allow shorts filtering in mobile youtube.

### Did you write a uBlock filter solving this?

m.youtube.com##ytm-search ytm-thumbnail-overlay-time-status-renderer[data-style="SHORTS"]:upward(ytm-video-with-context-renderer)

**Comment by xvello** [comment]
Thanks @chedanix, I'm implementing it in https://github.com/letsblockit/letsblockit/pull/485. We already had a rule for mobile seach, but it targets a different container class. I just added a second container class to the `upward` search instead of duplicating the whole rule. This should lead to better performance.
Feel free to open a PR next time if you feel comfortable doing it!

**Comment by xvello** [comment]
Also, it seems like you have two github accounts: @chedani and @chedanix. I credited the first one as it's already in our contributor list, but I can switch to the second one if that's the one you plan on keeping.

**Comment by chedanix** [comment]
Thanks @xvello. Please switch to @chedanix as the other one is my work account. The rule in the PR looks good. I didn't know you could use comma.

**Comment by xvello** [comment]
Done and done!

New version will be deployed in a couple of minutes. Your browser will get the updated rules in less than 24h, but you can [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it!
