### ISSUE TITLE
Update HN dark mode to mimic lemmy/kbin dark themes

### ISSUE THREAD

**Issue by tepozoa** [letsblockit/letsblockit#487]
### What filter does this issue target?

hackernews-darkmode

### What changes should be made?

Opinion: the existing HN dark mode is a bit harsh (full white on full black) for readability; with a few minor changes we can mimic the usability of the lemmy and kbin oriented dark themes, which are a bit softer on the eyes for reading.

### Did you write a uBlock filter solving this?

```
news.ycombinator.com##html:style(filter:invert(100%) hue-rotate(180deg))
news.ycombinator.com##body:style(background: #dddddd)
news.ycombinator.com##tbody:style(background: #cfcfcf)
news.ycombinator.com##div.toptext:style(color: #222222)
news.ycombinator.com###hnmain td[bgcolor="#222222"]
```

### Additional notes

The only downside is the HN titlebar loses it's orange background color - they use two nested tables, with the second table not having any ID to key on to differentiate them (which I could figure out, maybe someone else can(. Hence, it requires setting a global `tbody` in order to work as intended for the lower/2nd nested table. The orange outline is still retained, though to make it a unique visual element.

**Comment by xvello** [comment]
Hello @tepozoa, thanks for your suggestion! Copying before & after screenshots for reference:

![image](https://github.com/letsblockit/letsblockit/assets/6241083/0fef9016-8435-48cc-a939-6b436416cb1f)

![image](https://github.com/letsblockit/letsblockit/assets/6241083/827bdc87-7769-4370-9134-24faf3a458d1)

I'm the kind of person how chooses the "AMOLED black" theme in apps, and that's why I went with a `#000` background. I completely agree that it can be made better, so let's discuss it.

Looking at the screenshot, I'm worried about the low contrast between the grey text on the metadata line and the background. Although the HN markup will not change soon, let's not override too many styles though, let's try out a darker background, between two options?

**Comment by xvello** [comment]
For reference, here's the same screen portion with the default styles, contrast is pretty  bad out-of-the-box and I forgot about that :confused: 

![image](https://github.com/letsblockit/letsblockit/assets/6241083/b84915df-47e2-4182-8958-af1d857bd184)

**Comment by xvello** [comment]
Nice!

Because there would be too many classes to override to brighten the gray text and links, I suggest the following background color, in the middle:

```adblock
news.ycombinator.com##body:style(background: #eee)
news.ycombinator.com##tbody:style(background: #eee)
news.ycombinator.com##:matches-path("/item") tbody:style(background: #ddd)`
```

Could you please explain what the last two rules are achieving?

**Comment by xvello** [comment]
My question was about the following two rules, they are not in the version currently published:

```adblock
  news.ycombinator.com##div.toptext:style(color: #222222)
  news.ycombinator.com###hnmain td[bgcolor="#222222"]
```

Disabling them does not have an obvious effect.

**Comment by xvello** [comment]
Ah, right! IIRC that's the black banner that is sometimes displayed at the top of the pages.

**Comment by BPower0036** [comment]
@xvello Since I don't use hackernews. I don't speak out a preference, but I think that the proposed rules are good.

**Comment by xvello** [comment]
Heya @tepozoa, I updated https://github.com/letsblockit/letsblockit/pull/488 with the latest rules. The last thing I'd like to address before merging is the black bar created by the `#pagespace` element. I cannot manage to style it in dark grey, and it kind of sticks out:

![image](https://github.com/letsblockit/letsblockit/assets/6241083/f24c59ac-bf11-4fba-a3eb-64fd89803877)

**Comment by xvello** [comment]
Thanks for digging into the `bgcolor` stuff, and I agree about less orange being better. I'm updating the PR and releasing it!

**Comment by xvello** [comment]
The changes are live at https://letsblock.it/filters/hackernews-darkmode, congrats @tepozoa on your first contribution! Feel free to reach out if you have more suggestions to improve the project.

**Comment by xvello** [comment]
Heya @tepozoa, thanks for the ping.

I think the current rule is ok, here's my reasoning:
  - the original markup is `bgcolor="#000000"`, a black bar, that shows white after the CSS `invert` filter
  - the current rule `#hnmain td[bgcolor="#000000"]` matches it and hides it
  - the alternative would be to re-style it black with a `:style` directive (well, style it while so that it shows up black), but black on black won't show up anyway. This is why I elected to just remove it instead of re-styling it.
  - due to it being short-lived, I'd rather go with a simple solution
