### ISSUE TITLE
Dark mode for sites supporting it by built-in dedicated classes

### ISSUE THREAD

**Issue by Totogro** [letsblockit/letsblockit#489]
### What website(s) would this filter apply to?

messenger.com

### What content should be blocked?

Some DOM elements have a class="__fb-light-mode" that turns perfectly well to a nice dark mode if it is changed to class="__fb-dark-mode", but the site does not offer the option to switch this (apart from the facebook.com domain)
It would be nice if this followed the browser settings.
This is pretty trivial to do in JS but I have no idea how to do it with uBlock Origin rules...

**Comment by BPower0036** [comment]
@Totogro currently uBlock Origin nor AdGuard support rules that can change the name of classes.

**Comment by xvello** [comment]
Hello @Totogro, thanks for suggesting this! I'm gonna close it though, because:

- while uBO rules can remove classes with the `:remove-class` action, they cannot inject new classes. That's a security measure to make sure that the rules engine cannot be used by malicious actors. For this kind of advanced DOM manipulation, you'll want to look at userscripts engines such as [Tampermonkey](https://addons.mozilla.org/firefox/addon/tampermonkey?utm_source=usz)
- Meta's websites are not and will not be supported by this project
