### ISSUE TITLE
Filter out "market partner" (reseller) results from Woolworths

### ISSUE THREAD

**Issue by sammcj** [letsblockit/letsblockit#496]
### What website(s) would this filter apply to?

www.woolworths.com.au

### What content should be blocked?

Woolworths tries to sell you items from their "market partners" when you're doing your shopping online.

You cannot disable these ads in your settings - so I came up with a small filter to remove them.

### Did you write a custom uBlock filter already?

Yes!

```
! https://www.woolworths.com.au Filter out market partner (reseller) ads
www.woolworths.com.au##div.ng-star-inserted.product-grid-v2--tile:has-text(Sold by Market Partner)
```

**Comment by xvello** [comment]
Hello @sammcj, thanks for the suggestion!

I do have a similar custom rule in my list for a french retailer with the same marketplace nonsense, but I didn't add it to this project because I assumed it would not benefit enough users. I might be wrong though. Looking at the server access logs, I actually see 18 different users from Australia (and 24 from France!), so let's go with it and see if people enable it!

As with the other PR, I prefer to avoid using `:has-text()` so I want to investigate whether there's another way to match. Navigating through product categories, I could not find any such marketplace product, could you please provide me with a URL that show such elements?

**Comment by BPower0036** [comment]
@MasterKia the problem with `:has-text` is, that the text in depended on the language and `:upward` might have a better performance.

**Comment by xvello** [comment]
@MasterKia please do not make bold claims without backing them with evidence. Here is what's happening when uBlockOrigin evaluates a `:has-text` selector:

- [PSelectorHasTextTask](https://github.com/gorhill/uBlock/blob/8d09c562ab209fc2683e7f72f40c6eb67bb67c3c/src/js/html-filtering.js#L71-L80) is called, which gets the target text with `node.textContent`
- The [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) for that function states that it "returns the concatenation of the textContent of every child node, excluding comments and processing instructions"
- In the Firefox engine, [OnQueryTextContent](https://github.com/bolucat/Firefox/blob/9a5df599eafe84d7ed6e429676248ab73dd6f52d/dom/events/ContentEventHandler.cpp#L1481-L1523) allocates a new string and calls [GenerateFlatTextContent](https://github.com/bolucat/Firefox/blob/9a5df599eafe84d7ed6e429676248ab73dd6f52d/dom/events/ContentEventHandler.cpp#L747C31-L801) to fill it. That function has to navigate down the element's children to compute and concatenate all of the text contents, every time it is called
- For comparaison, here's the much shorter [Attr::GetValue](https://github.com/bolucat/Firefox/blob/9a5df599eafe84d7ed6e429676248ab73dd6f52d/dom/base/Attr.cpp#L137-L145) function, that is called when you write a `a[title^="my-prefix"]` rule. It just returns a pointer to a pre-computed value stored in a hashmap

To add insult to injury, I could not find any caching in the code path towards `GenerateFlatTextContent`, which leads me to believe that every single rule will incur the whole extraction cost again, which is an issue for configurable templates like this one, that create one rule per input value. I am happy to be proven wrong if you have evidence of caching being used to amortize that cost.

This is the evidence on which I base my opinion that `:has-text` is wasteful and should not be used if CSS selectors are possible. Furthermore, this function encourages bad practices such as:
  - calling it on the whole parent element instead of targeting the smallest possible scope, which amplifies this performance issue. For example, the suggested rule runs `:has-text` on the whole item card, instead of just the store link element
  - matching on displayed text instead of semantic information, which makes rules brittle and dependent on the user's display language

**Comment by sammcj** [comment]
Sorry running way behind this week - I'll probably do this in the weekend as work is crazy. If the issue is an eyesore feel free to close it but I'll still submit a PR for consideration.

**Comment by xvello** [comment]
Hey @sammcj, not a problem, it's a weekend project with no deadlines, don't sweat it!


I finally found some marketplace results while [searching for orange](https://www.woolworths.com.au/shop/search/products?searchTerm=orange&pageNumber=1&sortBy=TraderRelevance&filter=SoldBy(Everyday%20Market%20partners)). Could you please test the following rule:

```adblock
www.woolworths.com.au###search-content shared-product-vendor-message:upward(div.product-grid-v2--tile)
```

What it does:

- only apply within `#search-content`, as in an element with a `search-content` id
- search for `shared-product-vendor-message` elements (the line that gives the vendor name
- find the parent that matches `div.product-grid-v2--tile` (a `div` with the class `product-grid-v2--tile`) and hide it

Browsing the search, I found these non-product tiles pretty obnoxious, here's how to remove them too:
```adblock
www.woolworths.com.au###search-content shared-inspiration-tile:upward(div)
```

**Comment by sammcj** [comment]
They both work perfectly @xvello!

It might seem petty to some folks outside of Australia but they're a for-profit company that has been price gouging and exploiting such a huge portion of the population. Add to this the cheek of then trying to people items from third parties (they don't even arrive with your shopping - and can incur extra shipping charges). I know so many people that are annoyed by this behaviour I know 5 people that are already using my crappy v1 filter 😅.

I'll have a crack at submitting a PR this morning.

**Comment by sammcj** [comment]
I've got a draft PR - I just not quite sure on the correct way of doing the tests for a specific URL path after the domain, I think I'm fundamentally misunderstanding the tests and might need to RTFM 😅 

https://github.com/letsblockit/letsblockit/pull/514

**Comment by JohnyP36** [comment]
@sammcj The rules you put under the `params` must be the same as the rules above. 
See what I changed at https://github.com/letsblockit/letsblockit/pull/514/commits/7818e5909042476b7ba3153a7fa4031c765f2e4b

**Comment by xvello** [comment]
The new template is live at https://letsblock.it/filters/woolworths-cleanup, thanks a lot for your contributions!

**Comment by sammcj** [comment]
Sorry I missed your comment @JohnyP36, I appreciate you taking the time to fix it up! Thanks again for your help @xvello  🎉
