### ISSUE TITLE
Hacker News: Anonymize Hacker News Comments (Removes HN usernames from comments)

### ISSUE THREAD

**Issue by someguyinbaltimore** [letsblockit/letsblockit#530]
### What website(s) would this filter apply to?

https://news.ycombinator.com/

### What content should be blocked?

(Removes HN usernames from comments)

**BEFORE:**
![image](https://github.com/letsblockit/letsblockit/assets/9001416/37c6c2e7-0ad3-4ce7-a72a-9cac9c95767b)

**AFTER:**
![image](https://github.com/letsblockit/letsblockit/assets/9001416/cb0963ef-febc-4907-b715-b79e7d44de79)

### What options should be offered?

No options for this particular filter. (Also this question isn't marked as required) but seems to be required to submit. 

### Did you write a custom uBlock filter already?

! 2023-08-14 https://news.ycombinator.com
news.ycombinator.com## td > table > tbody > tr > .default > div > .comhead > .hnuser

### Additional notes

Inspiration: https://news.ycombinator.com/item?id=37123961

**Comment by xvello** [comment]
Hello @someguyinbaltimore, thanks for the suggestion!

Would you like to try opening a PR to add it yourself?

Adding a template is achieved by adding a yaml file to the repo, you can just copy [hackernews-darkmode.yaml](https://github.com/letsblockit/letsblockit/blob/main/data/filters/templates/hackernews-darkmode.yaml) as `hackernews-usernames` and modify it. [data/filters/README.md](https://github.com/letsblockit/letsblockit/blob/main/data/filters/README.md) documents the file format. Because the template does not have any option, tests are not needed.

- The rule can be simplified as ` news.ycombinator.com##.comhead .hnuser`
- There will be other suggestions of such rules, in which case we'll transition to a modular `hackernews-cleanup` template, similar to [woolworths-cleanup](https://github.com/letsblockit/letsblockit/blob/main/data/filters/templates/woolworths-cleanup.yaml) and others. If you want to directly start this way, it would be preferable.

Cheers!

**Comment by xvello** [comment]
Heya @someguyinbaltimore, thanks for your contribution. Is is now part of https://letsblock.it/filters/hackernews-cleanup

**Comment by someguyinbaltimore** [comment]
Hello Xavier, I'm sorry I missed your email in Aug. I would have totally
tried to do it. But I had a lot going on. I'm glad to see you completed it.
Have a great week! Cheers..
