### ISSUE TITLE
Non-intrusive usage for `temu.com`

### ISSUE THREAD

**Issue by keks24** [letsblockit/letsblockit#533]
### What website(s) would this filter apply to?

https://www.temu.com/

### What content should be blocked?

`Intrusive pop-ups` and `psychological triggers` like:
* 90% OFF!!
* ONLY 2 ARTICLES LEFT!
* 175 CUSTOMERS ALSO HAVE THIS ARTICLE IN THEIR SHOPPING CART!
* Quick, buy now!
* Do you really want to remove this article from your shopping cart? You will miss out the awesome discount!

### Did you write a custom uBlock filter already?

[my-ublock-static-filters_2023-08-17_14.37.07.txt](https://github.com/letsblockit/letsblockit/files/12369457/my-ublock-static-filters_2023-08-17_14.37.07.txt)

### Additional notes

The static filters are not perfect on all websites.

It is also very aligned to my needs. Things, like the `strikedthrough original total price` and `discount percentages`, are blocked.

Intrusive things, like `stopping me from my decision` and `begging to reconsider`, are blocked as well.

**Comment by keks24** [comment]
@JohnyP36, thanks for the quick reply!

I see!

I can try to figure something out to make the filter rules more generic, but I am not very good at defining filter rules.

Most of the stuff is coming from `kwcdn.com`, but blocking this breaks the entire page:

![20230817T165946+0200_screenshot](https://github.com/letsblockit/letsblockit/assets/13721064/41d66169-b34a-45dd-a160-c9b63843cf4f)

**Comment by JohnyP36** [comment]
@keks24 When I have time (probably somewhere within 3 months) I can make an account and verify and beautify your rules, but you have to be patient.

**Comment by keks24** [comment]
Nice, just within 3 days?! (Measuring in adult time) :smile:

Sure thing, no pressure!

I am also going to invest some time and will update here from time to time.

**Comment by xvello** [comment]
Hello @keks24, thanks a lot for your contribution to the project!

My intuition is that this template would be a pretty high-maintenance one:

- their markup use autogenerated class names, for which we have no guarantee of stability. They could all change next month, invalidating all of the rules
- there will probably be additions or changes of these prompts all year long, as they A/B test their conversion rate

This is definitely not a template that the contributors team can maintain on a reactive mode (not using the target website and waiting for people to open issues when it breaks). I think that the best way forward would be for you to commit to maintain it proactively and contribute updates as needed.

Because the scope of things to hide will vary repeatedly as nags are added and removed, I don't recommend making a customizable template that lists the things it hides. I'd go with a "remove all of that stuff" non-customizable template like we do for the high-maintenance [youtube-shorts.yaml](https://github.com/letsblockit/letsblockit/blob/main/data/filters/templates/youtube-shorts.yaml). To make the maintenance easier, I'd rather you add comments that explain what the rule hide, like we do for the shorts template.

How would you feel about giving it a try? I'm happy to help and review it of course! Adding a template is achieved by adding a yaml file to the repo, you can just copy [youtube-shorts.yaml](https://github.com/letsblockit/letsblockit/blob/main/data/filters/templates/youtube-shorts.yaml) as `temu-cleanup` and modify it. [data/filters/README.md](https://github.com/letsblockit/letsblockit/blob/main/data/filters/README.md) documents the file format. Because this template will not have any option, tests are not needed.

**Comment by keks24** [comment]
@xvello

>  I think that the best way forward would be for you to commit to maintain it proactively and contribute updates as needed.

> How would you feel about giving it a try?

I feel honoured to get this kind of opportunity!

But I am not sure, if I will be capable of maintaining `proactively` on a `regular basis`, since my current living situation still has some incoming unpredictable twists and turns.

> To make the maintenance easier, I'd rather you add comments that explain what the rule hide, like we do for the shorts template.

Sure!

I will have a look later on and will see, if I can do it. :grin:

**Comment by keks24** [comment]
I thought about it and I want to give it a try!

Though, I still have not looked into the `yaml` files in detail and still need to figure out how the process flow looks like.

I can maintain it proactively from time to time, but it will be very irregularly later on, if this would be OK.

**Comment by xvello** [comment]
Hello @keks24, sorry for the delay! This month has been busy and I'll be out of town for the rest of the month. Feel free to open a PR as I described above (by copying youtube-shorts.yaml and changing the rules). I won't be able to test the rules, but can review and merge it.

**Comment by keks24** [comment]
@xvello, sure! Once I found the time to do it finally.

I am currently prioritising personal goals. I will come back later to this.

Meanwhile, temu.com may have changed a lot of things already, so less editing for me, if I would have started now. :smile:

**Comment by keks24** [comment]
I just want to inform you, that I do not have the capacities for this anymore, sorry.

**Comment by xvello** [comment]
Hello @keks24, thanks for the head's-up. Re-closing as "not done" to better reflect the status, but happy to re-open if someone wants to start work on this!
