### ISSUE TITLE
Google-search-cleanup: "People also search for" is not blocked on mobile versions

### ISSUE THREAD

**Issue by opzch** [letsblockit/letsblockit#546]
### What filter does this issue target?

https://letsblock.it/filters/google-search-cleanup

### What changes should be made?

Checked with: desktop chromium + uBlock origin, android chromium + Adguard, android firefox + uBlock origin, android kiwi browser + uBlock origin.

Link:
https://www.google.com/search?q=remove+people+also+search+for&ie=UTF-8&hl=en

![1](https://github.com/letsblockit/letsblockit/assets/99139463/1c441499-4dc1-453f-95e2-2aeda8a570a2)
![2](https://github.com/letsblockit/letsblockit/assets/99139463/edab3337-c60d-4df9-89dc-91227a8e7142)

### Did you write a uBlock filter solving this?

No

**Comment by BPower0036** [comment]
Can't reproduce. Can you give a better screenshot of the html code of that google page?

**Comment by JohnyP36** [comment]
> Can't reproduce. Can you give a better screenshot of the html code of that google page?

I only get "People also ask" which is properly blocked by the template.

**Comment by xvello** [comment]
Hello @opzch, thanks for opening an issue!

Currently, the only templates that have tested mobile support are youtube and nebula. It's very probable that google search returns a different markup that would need a whole different set of rules. For now, mobile support is best effort for most templates.

You'll notice the out rules currently start with `#rso` (which means an element of `id="rso"` in order to not match non-search pages on the same domain. We'll need a check the DOM higher than your screenshot, to confirm the `#rso` element is still on mobile.

I'll be out of town for two weeks and won't have the time to look into this, but happy to review and merge a PR if another contributor manages to update the rule.

**Comment by xvello** [comment]
Hey @opzch,

Thanks to @JohnyP36, the update has just been deployed! Your browser will get the update in less than 24h, but you can [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it!
