### ISSUE TITLE
Block low view videos

### ISSUE THREAD

**Issue by TryFIXed** [letsblockit/letsblockit#596]
### What website(s) would this filter apply to?

https://www.youtube.com/

### What content should be blocked?

On the start page, every Video that is under a configurable view amount shouldn't be shown.

### What options should be offered?

the cap of views needed to be shown

### Additional notes

I think it could be a cool filter because, currently youtube tends to recommend low views youtube videos that are most of the time also of low quality. very important is that this filter is only for the start page bcs you dont want to see only high view count videos when ur searching for something.

**Comment by Nomes77** [comment]
Currently, such rule would be `##ytd-browse ytd-rich-item-renderer:has(.inline-metadata-item.ytd-video-meta-block:has-text(10K view))`. However, we can't make the numbers dynastically match.

**Comment by JohnyP36** [comment]
> However, we can't make the numbers dynastically match.
Such rule is also language specific.

**Comment by xvello** [comment]
Hello @TryFIXed and thanks for your idea!

While it looks easy at first glance (just check whether `video.views < threshold`), our content blocking rules only have access to the textual representation. We could get smart with regexps, such as this one for videos under 1000 views:
```adblock
www.youtube.com##ytd-browse[page-subtype="home"] span.ytd-video-meta-block:has-text(/\d+\svues/):upward(ytd-rich-item-renderer)
``` 

But this rule is specific to my display language (French), and won't work in other languages, because the numbers are formatted differently in different languages. To work in English, it would need to be:
```adblock
www.youtube.com##ytd-browse[page-subtype="home"] span.ytd-video-meta-block:has-text(/\d+\sviews/):upward(ytd-rich-item-renderer)
``` 

Because our user base is international, I don't want to distribute rules that assume that the display language is English, and that's why I highly discourage matching on display strings. This is a limitation of this project: building on top of content blockers removes the burden of publishing a dedicated browser extension, but means that we cannot address every single use case.

As an example https://github.com/code-charity/youtube/issues/1833 discusses adding support for your use case in the ImprovedTube  extension.
