### ISSUE TITLE
Extend "YouTube: filter out videos by channel" to Google Search too

### ISSUE THREAD

**Issue by agostonbarna** [letsblockit/letsblockit#633]
### What website(s) would this filter apply to?

www.google.com, www.youtube.com

### What content should be blocked?

Filter out YouTube channels from Google Search results in addition to the YouTube search with the "YouTube: filter out videos by channel" filter.

### What options should be offered?

My proposal would be to add a checkbox to the "YouTube: filter out videos by channel" filter e.g. "Filter out YouTube channels from Google Search too", and if someone opts-in then the rules are also added to filter out the YouTube channels from the Google Search results.

Unfortunately, the YouTube channel's id e.g. "@ScreenCultureOfficial" is not available in the Google Search results, so the YouTube channel's display name would also need to be provided in the template e.g. "Screen Culture".

### Did you write a custom uBlock filter already?

```
www.google.com###rso > div:has(span:has-text(YouTube · Screen Culture))
www.google.com###rso div[data-surl^="https://www.youtube.com/"]:has(span:has-text(Screen Culture))
```
where "Screen Culture" is the YouTube channel's name that will be filtered out from the Google Search results.

### Additional notes

**Comment by xvello** [comment]
Hello @agostonbarna, thanks for the idea!

As you noted, this will prove tricky because we don't have a clear channel link to match on or a properly tagged channel identifier available. It is true that matching on the display name with `:has-text()` does work, but:

- users would need to input a different information (the display name instead of the channel ID), it cannot be a simple checkbox in https://letsblock.it/filters/youtube-channel, it would need to be its own separate template

- as far as I know, there's no way to set `:has-text` as an exact match, so it will hide anything with a text containing the channel name. Say a user inputs `Abba`, videos from a `Abbacusses` channel would also silently be hidden, which my perfectionist brain does not like. We could mitigate this by making use of the `·` dots that are currently used, and render the following rule

> www.google.com###rso > div:has(span:has-text(YouTube · Abba ·))

But this display convention might not be the same in all countries and might change tomorrow without notice. Overall, I think that we are reaching the technical capabilities of uBO and this project, and I would not recommend adding this template to the project. You can still add these rules to your list via https://letsblock.it/filters/custom-rules and sync it on all your devices.

**Comment by agostonbarna** [comment]
Hey @xvello 
Thanks for the feedback!
Oh, I wasn't aware that `:has-text()` uses a substring match instead of an exact match, but it indeed seems like the case. There is a regex version too where we could do a full text match e.g. `:has-text(/^YouTube · Channel name$/)`, but then the channel name might still need to be escaped to avoid being interpreted as some regex. That's maybe doable with the script that generates the patterns, but it's true that using the channel display might not be too reliable and might not worth the effort.
So I'll go with my own rules for this use case. It's a bit annoying to write them manually, but still less annoying than seeing some youtube channels in the google search 😃
